INSERT INTO ACCOUNT (ID, FIRSTNAME, SURNAME, ACCNUMBER) VALUES(1, 'John', 'Doe', '1234'); 

INSERT INTO ACCOUNT (ID, FIRSTNAME, SURNAME, ACCNUMBER) VALUES(2, 'Jane', 'Doe', '1235'); 

INSERT INTO ACCOUNT (ID, FIRSTNAME, SURNAME, ACCNUMBER) VALUES(3, 'Jim', 'Taylor', '1236'); 
